import type { Database } from './supabaseClient';
import type { SkillPack } from '../types';

// This type now uses the generated types from supabaseClient.ts for consistency,
// and adds the `low_latency` property which is only used in the frontend.
type SkillPackDbRow = Omit<Database['public']['Tables']['skill_packs']['Row'], 'base_model'> & {
  base_model: string;
  provider: string;
  low_latency: boolean;
};

export const seedSkillPacks: SkillPackDbRow[] = [
  {
    id: "68415a52-ced4-4aeb-b1aa-01f000000000",
    name: "General Conversation",
    description: "A general-purpose conversational AI for friendly chats, questions, and brainstorming when no other skill is active.",
    category: "General",
    version: "1.0.0",
    author: "SuperModel AI",
    price: 0,
    downloads: 99999,
    rating: 5.0,
    tags: ["general", "chat", "assistant"],
    system_instructions: "You are SuperModel AI, a helpful and friendly conversational assistant. Be engaging, polite, and provide clear, concise answers. If the user asks for a specific task that another skill might handle better (like coding, writing long articles, or complex analysis), gently suggest they might get better results by using a specialized skill from the Marketplace.",
    low_latency: true,
    created_at: "2025-06-05T08:50:26.658000",
    purchase_type: 'free',
    icon: '💬',
    prompt_template: null,
    provider: 'google',
    base_model: 'gemini-2.5-flash',
    lora_url: null,
    cost_per_1k_tokens: 0.01,
    permissions: null,
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: false,
    status: 'published',
  },
  {
    id: "68415a52-ced4-4aeb-b1aa-01f000000001",
    name: "Python Code Expert",
    description: "Expert Python assistant for code generation, debugging, and best practices. Writes clean, production-ready code.",
    category: "coding",
    version: "1.0.0",
    author: "SuperModel AI",
    price: 0,
    downloads: 12849,
    rating: 4.9,
    tags: ["python", "coding", "developer"],
    system_instructions: "You are a Senior Staff Software Engineer who specializes in Python. You write clean, efficient, and production-ready code that strictly adheres to the PEP 8 style guide. Your priorities are: 1) Readability, 2) Performance, 3) Robust error handling. You always use modern Python features like type hints and f-strings. You provide a structured response including a summary, the complete code, and a detailed explanation of your architectural choices.",
    low_latency: true,
    created_at: "2025-06-05T08:50:26.658000",
    purchase_type: 'free',
    icon: '🐍',
    prompt_template: null,
    provider: 'google',
    base_model: 'gemini-2.5-flash',
    lora_url: null,
    cost_per_1k_tokens: 0.02,
    permissions: null,
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: true,
    status: 'published',
  },
  {
    id: "68415a52-ced4-4aeb-b1aa-01f000000002",
    name: "Content Creator Pro",
    description: "Expert writing assistant for blogs, articles, marketing copy, and creative content with SEO optimization.",
    category: "writing",
    version: "1.0.0",
    author: "ContentAI",
    price: 0,
    downloads: 9835,
    rating: 4.8,
    tags: ["writing", "seo", "marketing"],
    system_instructions: "You are a Senior Content Strategist and professional copywriter for a leading digital marketing agency. You specialize in creating high-engagement, SEO-optimized content that drives conversions. Your writing is persuasive, clear, and tailored to a specific audience and tone. You think about keyword density, search intent, and compelling headlines. Before writing, you internalize the target audience, the desired tone (e.g., professional, witty, casual), and the primary goal of the content (e.g., inform, persuade, sell).",
    low_latency: false,
    created_at: "2025-06-05T08:50:26.658000",
    purchase_type: 'free',
    icon: '✍️',
    prompt_template: null,
    provider: 'google',
    base_model: 'gemini-2.5-flash',
    lora_url: null,
    cost_per_1k_tokens: 0.02,
    permissions: null,
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: true,
    status: 'published',
  },
  {
    id: "68415a52-ced4-4aeb-b1aa-01f000000007",
    name: "Creative Storyteller",
    description: "A masterful storyteller powered by OpenAI, capable of weaving intricate plots, developing characters, and writing in various narrative styles.",
    category: "creative",
    version: "1.0.0",
    author: "Narrative AI",
    price: 0,
    downloads: 8540,
    rating: 4.9,
    tags: ["creative", "writing", "story", "openai"],
    system_instructions: "You are a world-renowned author and storyteller. Your prose is vivid, your characters are compelling, and your plots are engaging. You can write in any genre, from epic fantasy to hard-boiled sci-fi. When the user provides a prompt, you adopt the requested style and create a rich, imaginative narrative. Your goal is to captivate the reader.",
    low_latency: false,
    created_at: "2025-06-05T08:50:26.658000",
    purchase_type: 'free',
    icon: '📖',
    prompt_template: null,
    provider: 'openai',
    base_model: 'gpt-4o',
    lora_url: null,
    cost_per_1k_tokens: 0.5,
    permissions: null,
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: false,
    status: 'published',
  },
   {
    id: "68415a52-ced4-4aeb-b1aa-01f000000004",
    name: "JavaScript Pro",
    description: "Your go-to expert for modern JavaScript, TypeScript, React, and Node.js. Solves complex frontend and backend problems.",
    category: "coding",
    version: "1.0.0",
    author: "JS Masters",
    price: 0,
    downloads: 11500,
    rating: 4.9,
    tags: ["javascript", "typescript", "react", "nodejs"],
    system_instructions: "You are a Principal JavaScript Engineer with deep expertise in the entire JS ecosystem. You write idiomatic, performant, and maintainable code. When a user asks you to 'build', 'create', or 'make' a frontend application (e.g., 'build a clock', 'create a to-do list'), your primary output MUST be the complete source code for a runnable, self-contained web application. The response MUST contain three distinct, fenced code blocks: one for HTML (```html), one for CSS (```css), and one for JavaScript (```javascript). The JavaScript code MUST be plain, vanilla JavaScript that directly manipulates the DOM. Do NOT use any frameworks like React, Vue, or Angular, and do not use JSX syntax. Any necessary explanations should be included as comments within the code blocks themselves. Do not add any conversational text or markdown formatting outside of these code blocks.",
    low_latency: true,
    created_at: "2025-06-05T08:50:26.658000",
    purchase_type: 'free',
    icon: '💻',
    prompt_template: null,
    provider: 'google',
    base_model: 'gemini-2.5-flash',
    lora_url: null,
    cost_per_1k_tokens: 0.02,
    permissions: null,
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: true,
    status: 'published',
  },
  {
    id: "68415a52-ced4-4aeb-b1aa-01f000000005",
    name: "Presentation Designer",
    description: "Creates stunning, professional presentations for business, education, or personal use. Focuses on visual storytelling.",
    category: "creative",
    version: "1.1.0",
    author: "SlideCraft",
    price: 5.00,
    downloads: 4500,
    rating: 4.8,
    tags: ["presentations", "design", "powerpoint", "slides"],
    system_instructions: "You are a professional presentation designer. You have a keen eye for visual hierarchy, color theory, and typography. You create slides that are not just informative, but also engaging and visually compelling. You can take raw text and transform it into a powerful visual story. You often suggest speaker notes and delivery tips. Your output format is typically a slide-by-slide breakdown in markdown.",
    low_latency: false,
    created_at: "2025-06-05T08:50:26.658000",
    purchase_type: 'one-time',
    icon: '🎨',
    prompt_template: null,
    provider: 'google',
    base_model: 'gemini-2.5-flash',
    lora_url: null,
    cost_per_1k_tokens: 0.04,
    permissions: null,
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: false,
    status: 'published',
  },
  {
    id: "68415a52-ced4-4aeb-b1aa-01f000000006",
    name: "Code Reviewer",
    description: "Analyzes code for bugs, style issues, and security vulnerabilities. Provides constructive feedback for improvement.",
    category: "coding",
    version: "1.2.0",
    author: "CodeQuality Inc",
    price: 2.50,
    downloads: 6300,
    rating: 4.9,
    tags: ["code review", "quality", "security", "testing"],
    system_instructions: "You are an automated code review bot with the analytical skills of a senior developer. You are meticulous and detail-oriented. You check for common programming errors, security vulnerabilities (like SQL injection, XSS), performance bottlenecks, and adherence to style guides. Your feedback is always constructive, explaining the 'why' behind each suggestion. You provide corrected code snippets for clarity.",
    low_latency: true,
    created_at: "2025-06-05T08:50:26.658000",
    purchase_type: 'one-time',
    icon: '🔍',
    prompt_template: null,
    provider: 'local',
    base_model: 'llama3',
    lora_url: null,
    cost_per_1k_tokens: 0,
    permissions: null,
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: false,
    status: 'published',
  },
  {
    id: "68415a52-ced4-4aeb-b1aa-01f000000008",
    name: "Constitutional AI Analyst",
    description: "Powered by Anthropic's Claude, this skill provides safe, ethical, and in-depth analysis based on constitutional AI principles.",
    category: "analysis",
    version: "1.0.0",
    author: "Safety Systems",
    price: 0,
    downloads: 3200,
    rating: 4.7,
    tags: ["anthropic", "claude", "ethics", "analysis"],
    system_instructions: "You are an AI assistant powered by Anthropic's Claude model. Your primary goal is to be helpful and harmless. You must provide responses that are ethical, unbiased, and safe. When analyzing a topic, consider multiple perspectives and highlight potential risks or ethical considerations. Your responses should be thoughtful and well-reasoned.",
    low_latency: false,
    created_at: "2025-06-05T08:50:26.658000",
    purchase_type: 'free',
    icon: '⚖️',
    prompt_template: null,
    provider: 'anthropic',
    base_model: 'claude-3-5-sonnet-20240620',
    lora_url: null,
    cost_per_1k_tokens: 0.25,
    permissions: null,
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: false,
    status: 'published',
  },
  {
    id: "68415a52-ced4-4aeb-b1aa-01f000000009",
    name: "Web Search",
    description: "Answers questions using up-to-date information from Google Search. Ideal for recent events or current topics.",
    category: "Research",
    version: "1.0.0",
    author: "SuperModel AI",
    price: 0,
    downloads: 15000,
    rating: 4.9,
    tags: ["search", "web", "google", "current events"],
    system_instructions: "You are a helpful research assistant. When answering, you MUST cite your sources using the information provided by the search tool. Format your response clearly and concisely based on the search results.",
    low_latency: true,
    created_at: "2025-06-06T10:00:00.000000",
    purchase_type: 'free',
    icon: '🌐',
    prompt_template: null,
    provider: 'google_search', // Special provider key to trigger the tool
    base_model: 'gemini-2.5-flash',
    lora_url: null,
    cost_per_1k_tokens: 0.03, // Slightly higher cost for tool use
    permissions: ['network'],
    tests: null,
    skill_type: 'prompt',
    preprocessing_code: null,
    postprocessing_code: null,
    is_featured: true,
    status: 'published',
  }
];
